"""Initial migration

Revision ID: 63c67529f31c
Revises: 
Create Date: 2026-04-05 17:29:40.611757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63c67529f31c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admins',
    sa.Column('AdminID', sa.String(length=20), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Department', sa.String(length=50), nullable=True),
    sa.Column('Contact', sa.String(length=100), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('AdminID')
    )
    op.create_table('AuditLog',
    sa.Column('LogID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.String(length=20), nullable=False),
    sa.Column('UserRole', sa.String(length=20), nullable=False),
    sa.Column('Action', sa.Enum('CREATE', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('TableAffected', sa.String(length=50), nullable=False),
    sa.Column('RecordID', sa.String(length=100), nullable=False),
    sa.Column('OldValue', sa.JSON(), nullable=True),
    sa.Column('NewValue', sa.JSON(), nullable=True),
    sa.Column('IPAddress', sa.String(length=45), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('LogID')
    )
    op.create_table('Faculty',
    sa.Column('FacultyID', sa.String(length=20), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Department', sa.String(length=50), nullable=False),
    sa.Column('Role', sa.Enum('faculty', 'hod'), nullable=True),
    sa.Column('Contact', sa.String(length=100), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('FacultyID')
    )
    op.create_table('Notifications',
    sa.Column('NotificationID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.String(length=20), nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=False),
    sa.Column('Message', sa.String(length=1000), nullable=False),
    sa.Column('Type', sa.Enum('grade_release', 'fee_deadline', 'warning', 'announcement', 'system'), nullable=True),
    sa.Column('IsRead', sa.Boolean(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('NotificationID')
    )
    op.create_table('Students',
    sa.Column('StudentID', sa.String(length=20), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Department', sa.String(length=50), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=False),
    sa.Column('Contact', sa.String(length=100), nullable=True),
    sa.Column('AcademicRecord', sa.Text(), nullable=True),
    sa.Column('FeeStatus', sa.Enum('Paid', 'Pending', 'Overdue'), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('ParentContact', sa.String(length=100), nullable=True),
    sa.Column('StudentPhone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('StudentID')
    )
    op.create_table('ExamStatus',
    sa.Column('ExamRecordID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudentID', sa.String(length=20), nullable=False),
    sa.Column('Semester', sa.String(length=100), nullable=False),
    sa.Column('GPA', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('ResultStatus', sa.Enum('Pass', 'Fail', 'ATKT', 'Distinction'), nullable=True),
    sa.Column('DateReleased', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['Students.StudentID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ExamRecordID'),
    sa.UniqueConstraint('StudentID', 'Semester')
    )
    op.create_table('FeeReceipts',
    sa.Column('ReceiptID', sa.String(length=20), nullable=False),
    sa.Column('StudentID', sa.String(length=20), nullable=False),
    sa.Column('FeeType', sa.String(length=50), nullable=False),
    sa.Column('Amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('PaidOn', sa.Date(), nullable=False),
    sa.Column('TransactionDetails', sa.Text(), nullable=True),
    sa.Column('Status', sa.Enum('Paid', 'Refunded', 'Cancelled'), nullable=True),
    sa.ForeignKeyConstraint(['StudentID'], ['Students.StudentID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ReceiptID')
    )
    op.create_table('Marksheets',
    sa.Column('StudentID', sa.String(length=20), nullable=False),
    sa.Column('Subject', sa.String(length=100), nullable=False),
    sa.Column('Semester', sa.String(length=100), nullable=False),
    sa.Column('Marks', sa.Integer(), nullable=False),
    sa.Column('Grade', sa.String(length=5), nullable=False),
    sa.Column('Credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['Students.StudentID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StudentID', 'Subject', 'Semester')
    )
    op.create_table('MiscellaneousRecords',
    sa.Column('RecordID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudentID', sa.String(length=20), nullable=False),
    sa.Column('RecordType', sa.Enum('Warning', 'Attendance', 'Leave', 'General'), nullable=True),
    sa.Column('Details', sa.Text(), nullable=False),
    sa.Column('RecordedBy', sa.String(length=100), nullable=False),
    sa.Column('RecordedOn', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['Students.StudentID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('RecordID')
    )
    op.drop_table('admins')
    op.drop_table('students')
    op.drop_table('feereceipts')
    op.drop_table('miscellaneousrecords')
    op.drop_table('marksheets')
    op.drop_table('faculty')
    op.drop_table('auditlog')
    op.drop_index(op.f('unique_exam'), table_name='examstatus')
    op.drop_table('examstatus')
    op.drop_table('notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('NotificationID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Message', mysql.TEXT(), nullable=False),
    sa.Column('Type', mysql.ENUM('grade_release', 'fee_deadline', 'warning', 'announcement', 'system'), server_default=sa.text("'system'"), nullable=True),
    sa.Column('IsRead', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('NotificationID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('examstatus',
    sa.Column('ExamRecordID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('StudentID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Semester', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('GPA', mysql.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('ResultStatus', mysql.ENUM('Pass', 'Fail', 'ATKT', 'Distinction'), server_default=sa.text("'Pass'"), nullable=True),
    sa.Column('DateReleased', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['students.StudentID'], name=op.f('examstatus_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ExamRecordID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('unique_exam'), 'examstatus', ['StudentID', 'Semester'], unique=True)
    op.create_table('auditlog',
    sa.Column('LogID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('UserRole', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Action', mysql.ENUM('CREATE', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('TableAffected', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('RecordID', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('OldValue', mysql.JSON(), nullable=True),
    sa.Column('NewValue', mysql.JSON(), nullable=True),
    sa.Column('IPAddress', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('Timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('LogID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('faculty',
    sa.Column('FacultyID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Department', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Role', mysql.ENUM('faculty', 'hod'), server_default=sa.text("'faculty'"), nullable=True),
    sa.Column('Contact', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('CreatedAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('FacultyID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('marksheets',
    sa.Column('StudentID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Subject', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Marks', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Grade', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('Semester', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Credits', mysql.INTEGER(), server_default=sa.text("'4'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['students.StudentID'], name=op.f('marksheets_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StudentID', 'Subject', 'Semester'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('miscellaneousrecords',
    sa.Column('RecordID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('StudentID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('RecordType', mysql.ENUM('Warning', 'Attendance', 'Leave', 'General'), server_default=sa.text("'General'"), nullable=True),
    sa.Column('Details', mysql.TEXT(), nullable=False),
    sa.Column('RecordedBy', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('RecordedOn', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['students.StudentID'], name=op.f('miscellaneousrecords_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('RecordID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('feereceipts',
    sa.Column('ReceiptID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('StudentID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('FeeType', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('PaidOn', sa.DATE(), nullable=False),
    sa.Column('TransactionDetails', mysql.TEXT(), nullable=True),
    sa.Column('Status', mysql.ENUM('Paid', 'Refunded', 'Cancelled'), server_default=sa.text("'Paid'"), nullable=True),
    sa.ForeignKeyConstraint(['StudentID'], ['students.StudentID'], name=op.f('feereceipts_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ReceiptID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('students',
    sa.Column('StudentID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Department', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Contact', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('AcademicRecord', mysql.TEXT(), nullable=True),
    sa.Column('FeeStatus', mysql.ENUM('Paid', 'Pending', 'Overdue'), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('DateOfBirth', sa.DATE(), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ParentContact', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StudentPhone', mysql.VARCHAR(length=100), nullable=True),
    sa.CheckConstraint('((`Year` >= 1) and (`Year` <= 4))', name=op.f('students_chk_1')),
    sa.PrimaryKeyConstraint('StudentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admins',
    sa.Column('AdminID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Department', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Contact', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('AdminID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('MiscellaneousRecords')
    op.drop_table('Marksheets')
    op.drop_table('FeeReceipts')
    op.drop_table('ExamStatus')
    op.drop_table('Students')
    op.drop_table('Notifications')
    op.drop_table('Faculty')
    op.drop_table('AuditLog')
    op.drop_table('Admins')
    # ### end Alembic commands ###
